### ISSUE TITLE
Error publishing project

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-3-Beta#15] opened 2021-12-21 18:10 UTC
Hi!

I’m testing Wisej 3.0.1.7 (beta). It’s working well, but in the publishing an error is occurring. Images are attached. Components do not load and I can’t see the contents of wisej.wx.

In previous versions everything is ok.

Thanks,
Ulisses.

![Site 1](https://user-images.githubusercontent.com/31284623/146945136-e9aa47e6-dc16-4ab4-a4df-6bb59afb8706.jpg)
![Site 2](https://user-images.githubusercontent.com/31284623/146945172-d3b51395-2160-4057-a347-6e0fc28416f1.jpg)

![Folder 1](https://user-images.githubusercontent.com/31284623/146945203-29919430-2ab7-44c8-ad95-1281499072fa.jpg)
![Folder 2](https://user-images.githubusercontent.com/31284623/146945221-e1290e8a-e1ca-4af6-a0ee-a5bdb06abbf0.jpg)
![Folder 3](https://user-images.githubusercontent.com/31284623/146945238-013c169d-bbd8-4e3e-b753-931bee7c740c.jpg)

_Originally posted by @ulissescappato in https://github.com/iceteagroup/Wisej-3-Beta/issues/13#issuecomment-998818697_

**Comment by FrankITG** [comment] 2021-12-21 18:11
Hi Ulisses,
do you have a web.config and also set up the correct .NET framework in it?

Best regards
Frank

**Comment by ulissescappato** [comment] 2021-12-21 18:21
@FrankITG, the test project is attached:

[Test.zip](https://github.com/iceteagroup/Wisej-3-Beta/files/7757251/Test.zip)

Thanks!

**Comment by FrankITG** [comment] 2021-12-21 21:51
Hi Ulisses,
handlers section in your web.config is empty.
Try adding this and see if it works.

```
  <handlers>
      <add name="json" verb="*" path="*.json" type="System.Web.HttpForbiddenHandler" />
      <add name="wisej" verb="*" path="*.wx" type="Wisej.Core.HttpHandler, Wisej.Framework"/>
    </handlers>

```

Best regards
Frank

**Comment by ulissescappato** [comment] 2021-12-21 22:31
@FrankITG. same issue here (1st picture).

Note that the project is in a subfolder of IIS and not the root. In previous versions of Wisej it works.

**Comment by AlaaTrAce** [comment] 2021-12-22 02:17
Hi @ulissescappato ,

Thank you for reporting this issue.
We will investigate it thoroughly and report back as soon as possible.

But just to make sure, did you follow the steps located here: [Deployment Documentation](https://docs.wisej.com/wisej-3-beta/asp.net-core/deployment#.net-framework)

Best,
Alaa

**Comment by ulissescappato** [comment] 2021-12-22 14:50
Hi, @FrankITG and @AlaaTrAce!

I developed a good test for you. Please, deploy the two folders of attached file in your local IIS. Wisej 2.5 works. Wisej 3 don't.

[comparison-wisej2-wisej3.zip](https://github.com/iceteagroup/Wisej-3-Beta/files/7763308/comparison-wisej2-wisej3.zip)

Thanks!

**Comment by lucapivato** [comment] 2022-01-19 20:51
@ulissescappato Thank you. Problem is still present in the latest beta-8. It's caused by the way ASP.NET Core handles the URL coming from IIS. Should be fixed in the next beta update, probably tomorrow.

**Closed** 2022-02-19 17:42 UTC
Labels: bug, resolved
